DROP TABLE IF EXISTS im_conversation_read;
DROP TABLE IF EXISTS im_message;
DROP TABLE IF EXISTS im_conversation;

CREATE TABLE im_conversation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conv_type TINYINT NOT NULL,
  user_id_a BIGINT,
  user_id_b BIGINT,
  team_id BIGINT,
  last_msg_id BIGINT,
  last_msg_preview VARCHAR(100),
  last_msg_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_private_pair UNIQUE (conv_type, user_id_a, user_id_b),
  CONSTRAINT uk_group_team UNIQUE (conv_type, team_id)
);

CREATE INDEX idx_last_msg_at ON im_conversation(last_msg_at);

CREATE TABLE im_message (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conv_id BIGINT NOT NULL,
  conv_type TINYINT NOT NULL,
  sender_id BIGINT NOT NULL,
  receiver_id BIGINT,
  team_id BIGINT,
  msg_type TINYINT NOT NULL DEFAULT 1,
  content VARCHAR(2000) NOT NULL,
  mention_all TINYINT NOT NULL DEFAULT 0,
  mention_user_ids VARCHAR(1000),
  related_type VARCHAR(50),
  related_id BIGINT,
  status TINYINT NOT NULL DEFAULT 1,
  recalled_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_conv_created ON im_message(conv_id, created_at, id);
CREATE INDEX idx_sender ON im_message(sender_id);
CREATE INDEX idx_team ON im_message(team_id);

CREATE TABLE im_conversation_read (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conv_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  last_read_msg_id BIGINT NOT NULL DEFAULT 0,
  read_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conv_user UNIQUE (conv_id, user_id)
);

CREATE INDEX idx_user ON im_conversation_read(user_id);
