DROP TABLE IF EXISTS activity_review_record;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS activity_comment;
DROP TABLE IF EXISTS activity_summary;
DROP TABLE IF EXISTS activity_checkin;
DROP TABLE IF EXISTS activity_waitlist;
DROP TABLE IF EXISTS activity_registration;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS activity_template;
DROP TABLE IF EXISTS activity_tag;

CREATE TABLE activity_tag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  category VARCHAR(50),
  usage_count INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_activity_tag_name UNIQUE (name)
);

CREATE TABLE activity_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL,
  description TEXT,
  default_tags JSON,
  default_duration INT DEFAULT 2,
  default_max_participants INT DEFAULT 20,
  safety_notes TEXT,
  cover_url VARCHAR(500),
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id BIGINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  tags JSON,
  cover_url VARCHAR(500),
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  reg_deadline TIMESTAMP NOT NULL,
  location_name VARCHAR(200),
  location_lat DECIMAL(10,7),
  location_lng DECIMAL(10,7),
  location_detail VARCHAR(500),
  max_participants INT NOT NULL DEFAULT 0,
  current_count INT NOT NULL DEFAULT 0,
  fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  status TINYINT NOT NULL DEFAULT 0,
  review_type TINYINT NOT NULL DEFAULT 0,
  is_team_only TINYINT NOT NULL DEFAULT 0,
  team_id BIGINT,
  template_id BIGINT,
  clone_from_id BIGINT,
  checkin_qr_code VARCHAR(500),
  location_verify TINYINT NOT NULL DEFAULT 0,
  location_radius INT NOT NULL DEFAULT 500,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_activity_location ON activity(location_lat, location_lng);

CREATE TABLE activity_review_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL,
  review_stage TINYINT NOT NULL,
  reviewer_id BIGINT,
  ai_result VARCHAR(20),
  ai_risk_level TINYINT,
  ai_risk_categories JSON,
  ai_reason TEXT,
  ai_confidence DECIMAL(4,3),
  final_result TINYINT NOT NULL,
  review_comment TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity_registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  active_key BIGINT NOT NULL DEFAULT 0,
  registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cancelled_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_activity_user_active UNIQUE (activity_id, user_id, active_key)
);

CREATE INDEX idx_activity_registration_activity_status ON activity_registration(activity_id, status);

CREATE TABLE activity_checkin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  checkin_lat DECIMAL(10,7),
  checkin_lng DECIMAL(10,7),
  checkin_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_activity_checkin_user UNIQUE (activity_id, user_id)
);

CREATE INDEX idx_activity_checkin_activity ON activity_checkin(activity_id, checkin_time);

CREATE TABLE activity_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL UNIQUE,
  creator_id BIGINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  image_urls JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity_comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  rating TINYINT NOT NULL,
  content VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_activity_comment_user UNIQUE (activity_id, user_id)
);

CREATE INDEX idx_activity_comment_activity_created ON activity_comment(activity_id, created_at);

CREATE TABLE activity_waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  queue_no INT NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  active_key BIGINT NOT NULL DEFAULT 0,
  pending_at TIMESTAMP,
  cancelled_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_activity_user_wait_active UNIQUE (activity_id, user_id, active_key),
  CONSTRAINT uk_activity_queue_no UNIQUE (activity_id, queue_no)
);

CREATE INDEX idx_activity_waitlist_activity_status_queue ON activity_waitlist(activity_id, status, queue_no);

CREATE TABLE notification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(100) NOT NULL,
  content VARCHAR(500) NOT NULL,
  related_type VARCHAR(50),
  related_id BIGINT,
  read_flag TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notification_user_read_created ON notification(user_id, read_flag, created_at);

INSERT INTO activity_template (name, category, description, default_tags, default_duration, default_max_participants, safety_notes, sort_order) VALUES
('运动健身', '运动健身', '适合跑步、羽毛球、飞盘等运动活动。', '["运动","健身"]', 2, 20, '活动前充分热身，量力而行。', 60),
('户外徒步', '户外徒步', '适合公园徒步、城市轻徒步等户外活动。', '["徒步","户外"]', 4, 30, '提前确认路线和天气，建议结伴行动。', 50),
('桌游聚会', '桌游聚会', '适合狼人杀、剧本杀、桌面游戏聚会。', '["桌游","聚会"]', 3, 12, '注意场地预约和活动时长。', 40),
('学习交流', '学习交流', '适合读书会、技术分享、语言角。', '["学习","交流"]', 2, 25, '提前准备主题材料。', 30),
('公益活动', '公益活动', '适合志愿服务、社区公益活动。', '["公益","志愿"]', 3, 50, '遵守组织方安全安排。', 20),
('城市探索', '城市探索', '适合城市漫步、展览打卡、文化探索。', '["城市探索","文化"]', 3, 20, '注意交通与集合时间。', 10);
