DROP TABLE IF EXISTS team_vote_record;
DROP TABLE IF EXISTS team_vote_option;
DROP TABLE IF EXISTS team_vote;
DROP TABLE IF EXISTS team_score_log;
DROP TABLE IF EXISTS team_file;
DROP TABLE IF EXISTS team_album;
DROP TABLE IF EXISTS team_announcement;
DROP TABLE IF EXISTS team_join_apply;
DROP TABLE IF EXISTS team_member;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS friend_apply;
DROP TABLE IF EXISTS friend_relation;
DROP TABLE IF EXISTS user_follow;

CREATE TABLE user_follow (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id BIGINT NOT NULL,
  following_id BIGINT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_follower_following UNIQUE (follower_id, following_id)
);

CREATE TABLE friend_relation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id_a BIGINT NOT NULL,
  user_id_b BIGINT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark_a VARCHAR(50),
  remark_b VARCHAR(50),
  group_a VARCHAR(50),
  group_b VARCHAR(50),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_friend_pair UNIQUE (user_id_a, user_id_b)
);

CREATE TABLE friend_apply (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  message VARCHAR(200),
  status TINYINT NOT NULL DEFAULT 0,
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  tags JSON,
  join_type TINYINT NOT NULL DEFAULT 1,
  max_members INT NOT NULL DEFAULT 100,
  member_count INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  score INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE team_member (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role TINYINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  score INT NOT NULL DEFAULT 0,
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_team_user UNIQUE (team_id, user_id)
);

CREATE INDEX idx_team_member_team_status ON team_member(team_id, status);
CREATE INDEX idx_team_member_user_status ON team_member(user_id, status);

CREATE TABLE team_join_apply (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  message VARCHAR(200),
  status TINYINT NOT NULL DEFAULT 0,
  reviewer_id BIGINT,
  reject_reason VARCHAR(200),
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_team_join_apply_team_status ON team_join_apply(team_id, status);
CREATE INDEX idx_team_join_apply_user_status ON team_join_apply(user_id, status);

CREATE TABLE team_announcement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  publisher_id BIGINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_team_announcement_team_created ON team_announcement(team_id, created_at);

CREATE TABLE team_album (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  description VARCHAR(200),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_team_album_team_created ON team_album(team_id, created_at);

CREATE TABLE team_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  file_name VARCHAR(200) NOT NULL,
  file_url VARCHAR(500) NOT NULL,
  file_size BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_team_file_team_created ON team_file(team_id, created_at);

CREATE TABLE team_score_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  score_change INT NOT NULL,
  action_type VARCHAR(50) NOT NULL,
  related_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_team_score_log_team_created ON team_score_log(team_id, created_at);
CREATE INDEX idx_team_score_log_user_created ON team_score_log(user_id, created_at);

CREATE TABLE team_vote (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  creator_id BIGINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  multiple TINYINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  deadline TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_team_vote_team_created ON team_vote(team_id, created_at);

CREATE TABLE team_vote_option (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_id BIGINT NOT NULL,
  content VARCHAR(100) NOT NULL,
  vote_count INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_team_vote_option_vote_sort ON team_vote_option(vote_id, sort_order);

CREATE TABLE team_vote_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_id BIGINT NOT NULL,
  option_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_team_vote_user_option UNIQUE (vote_id, user_id, option_id)
);

CREATE INDEX idx_team_vote_record_vote_user ON team_vote_record(vote_id, user_id);
